name: Docker Dev Image CI

on: [push]

jobs:
  push_to_registry:
    name: Push Docker image to Github Packages
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: get Rust version
        id: rust_version
        run: |
            echo "version=$(cat rust-toolchain | tr -d '\n')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Github Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Building container image
        uses: docker/build-push-action@v5
        with:
          push: false
          build-args: |
            TOOLCHAIN=${{ steps.rust_version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./Dockerfile.dev

      - name: Build container image
        uses: docker/build-push-action@v5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/rust-musl-builder:${{ steps.rust_version.outputs.version }}-llvm-cov-dev
          build-args: |
            TOOLCHAIN=${{ steps.rust_version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./Dockerfile.dev
